namespace Core.Entities.Oracle
{
    public partial class Transfor
    {
        public string Code { get; set; } = null!;
        public string? Descriptio { get; set; }
        public string? Address { get; set; }
        public string? Project { get; set; }
        public string? Assembly { get; set; }
        public string? User { get; set; }
        public string? Picture { get; set; }
        public byte? Symbol { get; set; }
        public byte? Phases { get; set; }
        public string? Metercode { get; set; }
        public decimal? Customers { get; set; }
        public decimal? Customer0 { get; set; }
        public decimal? Customer1 { get; set; }
        public decimal? Customer2 { get; set; }
        public string? Fparent { get; set; }
        public decimal? Xpos { get; set; }
        public decimal? Ypos { get; set; }
        public decimal? Z { get; set; }
        public byte? Xsize { get; set; }
        public byte? Ysize { get; set; }
        public string? Invnumber { get; set; }
        public bool? Datum { get; set; }
        public string? Owner { get; set; }
        public string? Owner1 { get; set; }
        public bool? Ison { get; set; }
        public decimal? R { get; set; }
        public decimal? G { get; set; }
        public decimal? B { get; set; }
        public string? Trftype { get; set; }
        public bool? Flag { get; set; }
        public string? Elnode { get; set; }
        public string? Lvelnode { get; set; }
        public string? Phnode { get; set; }
        public decimal? Mva3phScc { get; set; }
        public decimal? Mva1phScc { get; set; }
        public decimal? Culosses { get; set; }
        public decimal? Felosses { get; set; }
        public decimal? Impedance { get; set; }
        public bool? Group { get; set; }
        public string? Codebank { get; set; }
        public bool? Isopen { get; set; }
        public int? Municipio { get; set; }
        public byte? Dpto { get; set; }
        public string? Serial { get; set; }
        public string? Poblacion { get; set; }
        public DateTime? DateFab { get; set; }
        public DateTime? DateInst { get; set; }
        public bool? Type { get; set; }
        public bool? IsBank { get; set; }
        public bool? NumTrfs { get; set; }
        public decimal? Eneg { get; set; }
        public string? Marca { get; set; }
        public DateTime? DateRem { get; set; }
        public decimal? Latitud { get; set; }
        public string? TipoRed { get; set; }
        public decimal? Longitud { get; set; }
        public byte? Prstate { get; set; }
        public bool? Estado { get; set; }
        public bool? Clase { get; set; }
        public int? Zone { get; set; }
        public string? Powerdraw { get; set; }
        public bool? Health { get; set; }
        public decimal? Xoffset { get; set; }
        public decimal? Yoffset { get; set; }
        public decimal? Demanda { get; set; }
        public decimal? Ltotal { get; set; }
        public string? Tiposub { get; set; }
        public byte? Zonae { get; set; }
        public int? Idmercado { get; set; }
        public bool? Islight { get; set; }
        public bool? Deleted { get; set; }
        public string? Tfile { get; set; }
        public string? Valvula { get; set; }
        public string? Caso { get; set; }
        public bool? Ncalidad { get; set; }
        public bool? CruceSic { get; set; }
        public bool? Calitad { get; set; }
        public bool? Grupo { get; set; }
        public string? Connect { get; set; }
        public string? Owner2 { get; set; }
        public bool? Flag5 { get; set; }
        public bool? Pcv { get; set; }
        public string? Fparent2 { get; set; }
        public bool? Protocolo { get; set; }
        public byte? DepId { get; set; }
        public bool? Sequence { get; set; }
        public decimal? X { get; set; }
        public decimal? Y { get; set; }
        public string? CodSic { get; set; }
        public bool? Estadop { get; set; }
        public string? CodigoSui { get; set; }
        public int? CodigoSuiNum { get; set; }
        public string? Ownerid { get; set; }
        public string? Ownername { get; set; }
        public string? Ownertel { get; set; }
        public byte? Lifespan { get; set; }
        public string? Codetaxo { get; set; }
        public string? Grupo015 { get; set; }
        public string? Owner1h { get; set; }
        public string? Ownerh { get; set; }
        public string? Uia { get; set; }
        public string? Consecu015 { get; set; }
        public DateTime? DateRet { get; set; }
        public decimal? Rpp { get; set; }
        public bool? Iscri { get; set; }
        public bool? Iscrin { get; set; }
        public bool? Iscrinr { get; set; }
        public string? Uccap14 { get; set; }
        public decimal? Xmag { get; set; }
        public decimal? Ymag { get; set; }
        public bool? PendRemunera { get; set; }
        public bool? ControlGa { get; set; }
        public decimal? Eg { get; set; }
        public decimal? Pg { get; set; }
        public decimal? Egv { get; set; }
        public decimal? Cmp { get; set; }
        public decimal? Cme { get; set; }
        public decimal? Sp { get; set; }
        public decimal? Se { get; set; }
        public decimal? PromedioMinimoHora { get; set; }
        public decimal? Cme12 { get; set; }
        public decimal? Se12 { get; set; }
        public decimal? PromedioMinimoHora12 { get; set; }
        public decimal? Vsec1 { get; set; }
        public decimal? Vsec2 { get; set; }
        public decimal? Cra { get; set; }
        public bool? MigradoGa { get; set; }
    }
}
